// src/components/svelte/todo-list/index.svelte
<script lang="ts">
  let items = $state<string[]>([]);
  let input = $state('');

  function addItem() {
    if (!input.trim()) {return;}
    items = [...items, input.trim()];
    input = '';
  }

  function removeItem(index: number) {
    items = items.filter((_, i) => i !== index);
  }
</script>

<div class="todo-list">
  <div class="todo-input">
    <input
      type="text"
      bind:value={input}
      onkeydown={(e: KeyboardEvent) => e.key === 'Enter' && addItem()}
      placeholder="Add a todo..."
    />
    <button type="button" onclick={addItem}>Add</button>
  </div>
  <ul>
    {#each items as item, index}
      <li>
        <span>{item}</span>
        <button type="button" onclick={() => removeItem(index)}>×</button>
      </li>
    {/each}
  </ul>
  {#if items.length === 0}
    <p>No items yet</p>
  {/if}
</div>

// src/components/vue/todo-list/index.vue
<script setup lang="ts">
import { ref } from 'vue';

const items = ref<string[]>([]);
const input = ref('');

function addItem() {
  if (!input.value.trim()) {
    return;
  }
  items.value.push(input.value.trim());
  input.value = '';
}

function removeItem(index: number) {
  items.value.splice(index, 1);
}
</script>

<template>
  <div class="todo-list">
    <div class="todo-input">
      <input v-model="input" type="text" placeholder="Add a todo..." @keydown.enter="addItem" />
      <button type="button" @click="addItem">Add</button>
    </div>
    <ul>
      <li v-for="(item, index) in items" :key="index">
        <span>{{ item }}</span>
        <button type="button" @click="removeItem(index)">×</button>
      </li>
    </ul>
    <p v-if="items.length === 0">No items yet</p>
  </div>
</template>
