// src/components/vue/timer/index.vue
<script setup lang="ts">
import { ref, watch, onUnmounted } from 'vue';

const seconds = ref(0);
const running = ref(false);
let interval: ReturnType<typeof setInterval> | null = null;

watch(running, (isRunning) => {
  if (isRunning) {
    interval = setInterval(() => {
      seconds.value++;
    }, 1000);
  } else if (interval) {
    clearInterval(interval);
    interval = null;
  }
});

onUnmounted(() => {
  if (interval) {
    clearInterval(interval);
  }
});

function reset() {
  running.value = false;
  seconds.value = 0;
}
</script>

<template>
  <div class="timer">
    <span class="time">{{ seconds }}s</span>
    <button type="button" @click="running = !running">
      {{ running ? 'Pause' : 'Start' }}
    </button>
    <button type="button" @click="reset">Reset</button>
  </div>
</template>

// src/components/react/timer/index.tsx
import { useEffect, useState } from 'react';

export function Timer() {
  const [seconds, setSeconds] = useState(0);
  const [running, setRunning] = useState(false);

  useEffect(() => {
    if (!running) {
      return;
    }
    const interval = setInterval(() => {
      setSeconds((prev) => prev + 1);
    }, 1000);
    return () => clearInterval(interval);
  }, [running]);

  const reset = () => {
    setRunning(false);
    setSeconds(0);
  };

  return (
    <div className="timer">
      <span className="time">{seconds}s</span>
      <button type="button" onClick={() => setRunning(!running)}>
        {running ? 'Pause' : 'Start'}
      </button>
      <button type="button" onClick={reset}>
        Reset
      </button>
    </div>
  );
}
